### ISSUE TITLE
Aplication of parallel DoFHandler in Darcy flow

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1013]
- [x] Support for creating fields for individual components of DofHandler based on FeSystem.
      Modify FieldFE (and FeValueHandler) to accept composed dofhandler and use just particular component  
       in evaluation.
       Merge methods set_fe_data, set_native_dh. Parameter for VecMPI just optional crate own vector by
       default. Add parameter for component index in FeSystem (default value 0). Modify evaluation in 
       FeValueHandler to use this index instead of fixed index 0 used right now.

- [x] [blocking] (JS) #1008 DofHandler for lagrange mulitpliers

- [x] Replace MHDofhandler by native DH (in assembly)
- [x] Construct output fields for velocity and pressures directly from the result vector.
- [ ] Rename DarcyFlowMHOutput to DarcyMHPostproces. Generalize current postrpocessing and comparison to reference fields. (separate issue)
- [x] Remove usage of  fill_ouput_data. See stub pul request #1011. 
-  [x] (DF, JB) Pass parallel velocity field from DarcyFlow to Transport. Use FieldFE only.
- [x] Fix BDDC.
- [x] Parallel observe output. #628
- [ ] General field postprocessing. 

- calculation of FieldFE outputs (FieldFE, FEValueHandler and VectorSeqDouble) - results are incorrect

**Comment by jbrezmorf** [comment]
- Try to reimplement methods in LocalElementAccessorBase using DHCell accessor.
- remove unused methods
- For methods that are problematic identify places of their usage
- Try to minimize modifications of the assembly code, just replace various loops by loop over local or own DHCells.

**Comment by jbrezmorf** [comment]
**Removal of MHDH**

In LocalElementAccessorBase we need to change:
- uin ele_idx() ...
 - uint ele_row() - use dh_cell.get_dof_indices(), return value at correct position, used in:
   _LocalElementAccessorBase::ele_local_row_
   _AssemblyMH::set_dofs_and_bc_ (darcy_flow_assembly.hh)
   _AssemblyMH::assembly_dim_connections_ (darcy_flow_assembly.hh)
   _DarcyMH::allocate_mh_matrix_ (darcy_flow_mh.cc)
   _DarcyMH::assembly_source_term_ (2 uses, darcy_flow_mh.cc)
   _DarcyMH::set_mesh_data_for_bddc_ (darcy_flow_mh.cc)
   _DarcyMH::setup_time_term_ (darcy_flow_mh.cc)
   _RichardsLMH::read_initial_condition_ (richards_lmh.cc)
 - uint ele_local_row() - use dh_cell.get_loc_dof_indices(), return value at correct position, used in:
   _DarcyMH::read_initial_condition_ (darcy_flow_mh.cc)
   _DarcyMH::setup_time_term_ (darcy_flow_mh.cc)
 - uint edge_global_idx(uint i) - will be removed
   used only in _LocalElementAccessorBase::edge_local_idx_
 - uint edge_local_idx(uint i) - need special re-indexing array corresponding to the local order, used in:
   _AssemblyLMH::update_water_content_ (assembly_lmh.hh)
   _AssemblyLMH::assemble_sides_ (assembly_lmh.hh)
   _AssemblyLMH::assemble_source_term_ (assembly_lmh.hh)
 - uint edge_row(uint i) - use dh_cell.get_dof_indices(), return value at correct position, used in:
   _LocalElementAccessorBase::edge_local_row_
   _AssemblyLMH::assemble_source_term_ (assembly_lmh.hh)
   _AssemblyMH::set_dofs_and_bc_ (5 uses, darcy_flow_assembly.hh)
   _AssemblyMH::assembly_dim_connections_ (darcy_flow_assembly.hh)
   _DarcyMH::allocate_mh_matrix_ (3 uses, darcy_flow_mh.cc)
   _DarcyMH::set_mesh_data_for_bddc_ (2 uses, darcy_flow_mh.cc)
   _P0_CouplingAssembler::pressure_diff_ (mortar_assembly.cc)
   _P1_CouplingAssembler::add_sides_ (mortar_assembly.cc)
   _RichardsLMH::read_initial_condition_ (richards_lmh.cc)
 - uint edge_local_row( uint i) - use dh_cell.get_loc_dof_indices(), return value at correct position, used in:
   _AssemblyMH::set_dofs_and_bc_ (2 uses, darcy_flow_assembly.hh)
 - SideIter side(uint i) - without changes
 - uint side_global_idx(uint i) - will be removed
   used only in _LocalElementAccessorBase::side_local_idx_ and _side_row_
 - uint side_local_idx(uint i) - should use special array (same as in edge_local_idx)
   _AssemblyLMH::update_water_content_ (2 uses, assembly_lmh.hh)
   _AssemblyLMH::assemble_source_term_ (assembly_lmh.hh)
   _RichardsLMH::postprocess_ (2 uses, richards_lmh.cc)
 - uint side_row(uint i) - use dh_cell.get_dof_indices(), return value at correct position
   _LocalElementAccessorBase::side_local_row_
   _AssemblyMH::set_dofs_and_bc_ (3 uses, darcy_flow_assembly.hh)
   _AssemblyMH::add_fluxes_in_balance_matrix_ (2 uses, darcy_flow_assembly.hh)
   _DarcyMH::allocate_mh_matrix_ (darcy_flow_mh.cc)
   _DarcyMH::set_mesh_data_for_bddc_ (darcy_flow_mh.cc)
   _P0_CouplingAssembler::pressure_diff_ (mortar_assembly.cc)
   _RichardsLMH::postprocess_ (richards_lmh.cc)
 - uint side_local_row( uint i) - use dh_cell.get_loc_dof_indices(), return value at correct position
   _AssemblyMH::set_dofs_and_bc_ (darcy_flow_assembly.hh)

Then we can remove first argument (MH_DofHandler) from LocalElementAccessorBase constructor and appropriate data member.

----------------------

We need remove MH_DofHandler (data member mh_dh) in flow library, in following methods must be replaced:
 - _AssemblyMH::make_element_vector_ (darcy_flow_assembly.hh)
 - _DarcyMH::create_linear_system_ (3 uses, darcy_flow_mh.cc)
 - _DarcyMH::print_matlab_matrix_ (3 uses, darcy_flow_mh.cc) - can be removed
 - _DarcyMH::set_mesh_data_for_bddc_ (darcy_flow_mh.cc)
 - _DarcyMH::make_serial_scatter_ (4 uses, darcy_flow_mh.cc)
 - _RichardsLMH::initialize_specific_ (4 uses, richards_lmh.cc)

In previous methods are used methods and data members of MH_DofHandler:
 - side_flux()
 - side_dof()
 - prepare_parallel_bddc()
 - global_row_4_sub_row
 - side_row_4_id
 - side_ds, row_4_el
 - row_4_edge
 - edge_new_local_4_mesh_idx_

**Comment by jbrezmorf** [comment]
Resolution of remaining MHDH usages:
 - _AssemblyMH::make_element_vector_ (darcy_flow_assembly.hh)
	- can remove after we use output native velocity field 
 - _DarcyMH::create_linear_system_ (3 uses, darcy_flow_mh.cc)
        - use DH->local_size instead of mh_dh.global_row_4_sub_row->size()
        - replace ISCreateStride with ISCreateGeneral, pass though the DH cells and create vector of velocity
          dofs (side rows) and vector of pressure dofs (element rows).
 - _DarcyMH::print_matlab_matrix_ (3 uses, darcy_flow_mh.cc) - can be removed
 - _DarcyMH::set_mesh_data_for_bddc_ (darcy_flow_mh.cc)
 - _DarcyMH::make_serial_scatter_ (4 uses, darcy_flow_mh.cc)
 - _RichardsLMH::initialize_specific_ (4 uses, richards_lmh.cc)

In previous methods are used methods and data members of MH_DofHandler:
 - side_flux()
 - side_dof()
 - prepare_parallel_bddc()
 - global_row_4_sub_row
 - side_row_4_id
 - side_ds, row_4_el

**Comment by jbrezmorf** [comment]
- Introduce composed field FieldDivide, similar to FieldAddPotential. 
- Raname current "velocity" field to "flux".
- Use FieldDivide to introduce "velocity" field that is flux/cross_section.

**Comment by jbrezmorf** [comment]
**Replacement for P1 pressure**
- introduce field "pressure_p2_disc"
- compute DOFs of this field from dofs of "flux" and "pressure_p0" using  lines 610 - 629, value of "diff" on line 629 is DOF of the new field in single dof point.
- replace P1 reference values by "pressure_p2_disc" NODE_DATA output

**Comment by jbrezmorf** [comment]
- rename DH::lsize to n_own_dofs (make this change in master branch)
- introduce n_local_dofs
- try to fix assert in BDDC

**Comment by jbrezmorf** [comment]
- try to fix BDDC
- compute velocity in DG from the velocity field:
        - remove get_mh_dofhandler, replace by water->data["velocity"] and extraction of the FieldFE in 
          HC_ExplicitSequential::advection_process_step
	- move set_velocity_field from models into TransportDG, pass in the FieldFE of the velocity
        - modify TransportDG::compute_velocity to use FieldFE for the evaluation
- start modifications of convection transport (aka FV) #1064

**Comment by jbrezmorf** [comment]
@dflanderka : move remaining points into new issue, search for "postporocess" and "postprocessing"
to link related issues. Then close this issue.

**Comment by jbrezmorf** [comment]
Separate issue for Darcy output is: #658
=> closing
