### ISSUE TITLE
Input changes 4.0

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1439]
- [ ] Use vector valued BParser in FieldFormula
- [ ] normal field support
- [ ] support MSH4 for both input and output
- [ ] Allow HM to be passed as flow equation to the THC sequential, consider name change of the equations/coupling.
- [ ] Allow both DarcyFlowLMH and Richards to be the H eq. of HM coupling.
- [ ] THM coupling, allow (HT)-M or HM - T coupling.
- [ ] Time interpolation of the fields -> fixed THC seq. coupling for different time steps.
- [ ] Introduction of FieldComposed, input dictionary region: field, need support in the input
- [ ] FieldDescriptor without 'region' key.
- [ ] Allow output of the custom fields.

**Comment by Paulie14** [comment]
additional notes:
- [ ] T model with prescribed velocity field (probably included above)
- [ ] output of (permuted) computational mesh (is included in MSH4 support?)
- [ ] we talked about output of boundary fields

issue related notes:
- [ ] first two enable improving mechanics BC #1296
- [ ] issue #1169 make decision about raw output (+ngh output) 
- [ ] issue #1362 - possibly enable changing behaviour in input (?)

**Comment by jbrezmorf** [comment]
@Paulie14 comments incorporated into updated overview of changes.
