### ISSUE TITLE
Changes in input format

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#318]
Summary of changes in the main input file to consider in release 2.0.0

- [x] Sign of boundary fluxes, should it be positive for outer flux as is the convention in PDE, or positive for inner flux to be consistent with sign of sources (positive source is source-in)? Consult other software, 
and ProGeo. Make consistent balance output.
(unify with sources; #492)

- [x] In balance have only one output format. Table with values separated by tabs. Other formats through python formaters (script or module balance_format.py)
(OK)

- [x] consider naming boundary region sets with dots (.BOUNDARY and  .IMPLICIT_BOUNDARY),
consider shorter name for .IMPLICIT_BOUNDARY, is it even necessary?
(use renamed variant, merged in c369f9b)

- [x] Change vector valued fields to multi-fields with minimal change in inputs.
(Milan and Ales accept even the long variant: [ {TYPE=..}, {TYPE=...}, ...] without any conversions.
( #323 )

- [x] Is current input_fields list useful or is it better to set time line of every field x region independently
(Preserve current scheme of input_fields, but allow separated time sequences for individual fields.)
(Time sequences postponed to the next version)

- [x] consider region set as region #202
(Do it. Add individual regions into list of region sets. remove key "r_set" from the field descriptor)

- [x] Remove rid in field descriptor (for unnamed regions one can use id as the region name). 
(Can not do automatic transformation. Mark it OBSOLETE and remove in release 3.x, done in commit 7935c18)

- [x] allow list of regions in the field descriptor record #202
(declare region as an array, possibly postpone)

- [x] Simplify region setup in the mesh #386
(WIP)

- [x] auto conversions for: Mesh, ((Solver)) #386
( just for mesh, from the name of the mesh file, WIP)

- [x] !! better naming and structure of equations/couplings, #568 

- [x] !! better organize output, output_fields, balance, output_stream, possibly OutputStream should be Abstract, moving keys of format one level up,
  output_fields, balance and possibly other output stuff should be part of the output record,
( embed all output keys into output record more descriptive, 
consider rename output_stream key,
move output_fields list into current output_stream (perfectly possible with RecordGeneric)
) #494

- [x] !! allow output to more formats at the same time (both VTK and GMSH)
(just slight modification of output_stream)
However thing about native format for FieldFE (because of interupted calcualtions), and separate functionality to 
convert it into VTK or GMSH, etc. #494

- [x] !! default values for output file names
(OK)

**Comment by jbrezmorf** [comment]
done
