### ISSUE TITLE
reversible conversion tool

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#681]
**Features:**
- conversion rules implemented directly in Python using predefined set of actions and allowing
  to add new actions
- use ruamel.yaml lib to preserve comments, order of keys etc.
- conversion rules operates on YAML tree using natural dict and list like complex types
- organization of changes into: release change set > patch set > atomic changes
- atomic change is reversible (in some way)
- patch set have unique number, which is marked in the input file in order to apply patches only once
- release change sets are presented to the end users
- actions may by applied to the (simplified) IST in order to better check correctness of the actions
- every patch can be marked silent (suppress warnings)
- whole conversion could be run in silent or verbose mode

**TODO:**
- [ ] reader for IST, destile only necessary info, define how we store it
- [ ] implement current patches by simpler actions applied for path sets
- [ ] every action is class with methods for: forward/reverse, data/format (4 operations)
- [ ] Think how to deal with IRREVERSIBLE actions: 
  - regexp ops (not necessary)
  - merge keys, tags
  - merge lists
- [ ]

**Comment by jbrezmorf** [comment]
Implemented in [yaml_converter](https://github.com/flow123d/yaml_converter)
