### ISSUE TITLE
VTK general field data IO

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#855]
Make Writers independent of fields.
- [x] Move file unit_test/test1.pvd generated by some output unit test into directory output
- [x] Add rules to .gitignore for these files
- [x] Unify ElementDataCache and OutputData.
- [x] Use ElementDataCache instead of MeshData ...
- [x] Check that field.output(..) is called only from equation_output. (temporary rename) [ renamed, confirmed]
- [x] Move make_output_mesh from OutputTime into EquationOutput [+ EquationOutput moved into fields]
- [x]  Possibly pass output mesh into field.output(..) and field.observe_output(..) methods, move field evaluation code from OutputTime and Observe, respectively.
- [x]  Check if we can remove parameter `actual` of `BaseReader::get_element_data` [confirmed, removed]
- [x] How we use el_ids parameter of the same method in VTK reader to read only bulk or boundary data?
      We should retrieve bulk element ids	 and boundary element ids in check_compatible_mesh in the GMSH reader variant. Then we can replace passing the `el_ids` by `bool boundary_data` or similar.
- [x] move evaluation of fields and filling OutputData into Fields, pass created OutputData to register method
- [x] move writers into iolib 
- [x] support for reading PVD files. Can be implemented as another reader which have a cache of VTK readers for individual time steps. Can be implemented as another reader, using either table of VTK readers (big memory consumption) or internal instance of VTK for actual time.
- [x] Simplify mechanism to getting field values for given time. Do not use same structure fro internal data of reader and for public interface.
- [x] rename "gmsh_file" to "mesh_data_file" in FieldElementwise and FieldInterpolated ...

Implement Writer and Read for general FieldFE data as extension of VTK format.

VTK writer for arbitrary FE fields:
**Our extension of VTK:**
We write DOFs values on every element. This may by space inefficient but works fine in parallel a allow
to process the data by other tools then Flow123d. So we can possibly replace current output of internal flow data.
```
<Flow123dData Scalars=* Vectors =* Tensors=*>
<DataArray type=* Name=* format=* dof_handler_hash=*  n_dofs_per_element=*>
... n_elements x  n_dofs_per_element values
</DataArray>
...
</Flow123dData>
```
Attributes: 
	`dof_handler_hash` - should be unique identification of particular distribution of DOFs on particular mesh. To begin with use hash computed from number of elements of the mesh and number of dofs., 	
	`Name` the field name, 
	`n_dofs_per_element` number of DOF values of single element, i.e. size of the array is 
	number of elements times this attribute.

**TODO:**
- [x] Introduce `OutputType` `NATIVE_DATA`, this means output of FieldFE in our own format.
- [x] Introduce `Field<>::get_field_fe` which check that the field is in fact FieldFE set on all regions, return shared pointer to that FieldFE or NULL if the Field is not FieldFE.
- [x] Add support for NATIVE_DATA into Field<>::field_output. Use method get_field_fe, for NULL report warning and skip output, else call method of feild_fe that fills element data cache with DOF values, i.e.
pass through elements and read local DOF values on element from the global DOF vector.
- [x] Add writer for NATIVE_DATA.
- [x] Add our own XML tags to indicate FE type. (Paraview ignores unknown tags)

VTK reader for arbitrary FE fields:
- [x] For FieldFE input check the field type and for VTK reader check type of the tag for given field name. Have two kind of VTK field readers: Paraview field (see above), Native field, ... (TBD...)
 
- [x] Check that a DOF handler match field type in VTK file. (use `dof_handler_hash`)
- [x] If yes read the data into the vector. Pass through the elements read dofs on elements and assembly to
      the global vector, count number of writes in separate vector. Finally compute averages of values in the   global vector dividing them by the cont vector.
- [x] Implement interpolations between FE types. #823

**Comment by jbrezmorf** [comment]
closed by PR:  #866
