### ISSUE TITLE
Unified FieldFE

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#959]
Main issue for all work related to unification of FieldFE, FieldElemntwise and FieldInterpolatedP0.

related issues: 
#823, #774, #738, #618  - field interpolations
#826 - FieldFE on boundary mesh
#937 - mesh simplification (closed)

Tasks:

**FieldElementwise replacement**

- [x] Unify FieldFE and FeildElementwise for bulk elements.
- [x] Introduce Field<>::set_native_dh(shared_ptr<DofHandler>) which should be called after set_mesh. 
Postpone make_dohandler and check_a FieldFESpace struct to pass data about native dofhandler, maps etc. for particular input fields (init_conc, init_pressure, init_velocity, ...).
- [x] Implement necessary partitioning for BCMesh:
      - Pass through Boundaries in mesh, make partitioning of boundary elements, assign the proc number  same as in the connected bulk element.
      - Use Partitioning::id_maps to create id mapping vectors for BCMesh.
- [x] DoF handler for boundary elements (see also #826): Introduce a BCMesh ... wrapper class that operates only on BC elements (return ranges for boundary elements). This can be passed to DOF Handler to create boundary DOF map and then also boundary FiledFE.
      - Distinguish ElementAccesor::mesh_idx (should not be used out of Mesh) and ElementAccessor::idx ... unique only within particular bulk/bc mesh. Should be used in DofHandler.
- [x] @jstebel: DoF Handler with support for FE_P_disc<0>.
- [x] @jstebel: FeValues 'tensor_view'.
- [x] @jstebel: FeSystem for vectors of given spacedim, check that the vector spacedim match the FeValues space dim in FeValues constructor. Allow vector view for this case, similar for tensors (conductivity).
- [x] (TODO) Support for vector valued FiledFE, unit tests.
- [x] Support for tensor valued FiledFE, unit tests. Need specialization in FeShapeHandler for rank==2.
- [x] (TODO) Integration test for BC elementwise field.
- [x] FieldElementwise for BC input fields.
- [ ] @jbrezmorf: Support for init_velocity and init_trace_prassure in DarcyFlow. Support for velocity field in 
       solute transport. #966
- [ ] Integration test for velocity (vector valued) elementwise field.

**FieldInerpolatedP0 replacement**
related issues: #823, #774, #738, #618  
- [x] Introduce selection key 'interpolation'. Selection items: 'identic_mesh', 'equivalent_mesh', 'p0'.
      More interpolation types in future.

- [x] Apply BC DofHandler. 
                   Modify bulk interpolation in FeildFE to boundary interpolation as replacement of FieldInterpolatedP0. Algo: For every element T of target mesh find elements S of the source mesh, containing barycenter of T. Evaluate field in barycenter of T as average over values on element in the source mesh. 
- [x] (TODO) Generalization:
        - For resulting P0 fields we can take average from a general quadrature instead of just the barycenter on T.
- [x] Temporary solution. Force boundar FieldFE to be just P0 and use direct mapping form element index to DoF. 
- [x] Fix InterpolationP0.
- [x] Compare original interpolation algorithm based on intersections and algorithm based on higher order quadrature.

- [ ] JB, merge related issues

**Ideas**:
    - some generalization for non P0 target fields, need better weighted interpolation, or L2 projection
    - generalization of Interpolated P0: 
       - interpolation from bulk to boundary of: pressure P0, pressure native, conc P0, conc native; 
         velocity field native
       - interpolation from bulk to bulk (same input as before)
    - read any field given as FieldElementwise (in GMSH ElementData or in VTU CellData)        
      

**FieldElementwise native data**

- [x] IO test description: #962
- [x] @Paulie14: Test and implement native write and read for conc DG P0, P1, P2:#963
- [ ] Test and implement native write and read for velocity RT0: ... need usage of dof handler for passing velocity field. Introduce init_velocity in DarcyFlowMH, DarcyFlowLMH. Introduce velocity as input field for Transport ... 
- [x] (TODO) Replace usage of VecSeqDouble.create_field for velocity by usage of FieldFE based on DG RT0 dof handler. This also allows Native output of the velocity.
- [x] (TODO) VecSeqDouble, replace FieldElementwise by FieldFE, method create_field:  #961
- [x] @jstebel DofHandler for edge dofs.
- [ ] Test and implement native write and read for complete pressure field, in particular edge pressures. ...
       Need DofHandler for edge dofs.

**Comment by jbrezmorf** [comment]
All done or moved to new issues.
