### ISSUE TITLE
Use parallel DoFHandler

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#981]
New parallel DofHandler can not be used because of FieldFE is lack support for be based on parallel DoFHanlder and parallel outputs and not automatically used.
Related to:  #814, 

We need:
- [x] (JS) Have local numbering of Dofs incluing ghost dofs. Method DofHandler::get_loc_dof_indices working for ghost elements.

- [x]  (DF) Ranges (own_range, local_range - includs ghost cells), Accessor and Iterator for DofHandler Cells. FInish in #1014.

- [x] (DF) Replace VecSeqDouble with VecMPI. VecMPI constructor takes communicator as parameter, with default value PETSC_COMM_SELF. For this value we create just VecSeqWithArray. Replace VecSeqDouble constructors with a function caling VecMPI constructor with PETSC_COMM_SELF. ... for better readability.

- [x] (DF) VecMPI: move to la subdir

- [x] (DF) FieldFE (should know if it is based on serial or parallel DofHandler ??). For evaluation use 
DofHandler::get_loc_dof_indices. 

- [x] (DF) #1015 Use parallel DH in TransportDG:
- [x] (JS) #1012 Support for ghost values in VecMPI.

- [x] (DF, JB) FieldFE, method scatter to ghost dofs (must be called after values are changed and before evaluation). This calls scatter of VecMPI which in turn calls scatter for the VecGhost.

- [x] (JS) Support to create a serial DofHandler from a parallel DofHandler and associated Petsc scatter.

- [x] (DF) #1016 Output of parallel fields through serial output streams.

- [x] Apply parallel DH and output fields to Reactions.
- [x] Apply parallel DH and output fields to Transport. Need assembly based on DH. #1036

- [x]  #1013 Apply parallel DH and output fields to DracyFlow.

- [ ] Remove remaining (temporary) usages of cell_accessor_from_element (mainly in FieldFE)

**Comment by jbrezmorf** [comment]
Application of DH and velocity field in FV transport:
Computing side_flux from velocity:
"k is barycenter"
flux = arma::dot(velocity[sid][k], fe_values[sid]->normal_vector(k))*fe_values[sid]->JxW(k);
